### ISSUE TITLE
proxmox_virtual_environment_vm initialization stanza needs a boolean to disable cloud-init package updates

### ISSUE THREAD

**Issue by dmbrownlee** [bpg/terraform-provider-proxmox#1079]
Proxmox has a ciupgrade boolean that defaults to 1 (appears as "Upgrade packages: Yes" in the Proxmox web UI) and this causes the VM's package manager to update packages on first boot.  https://pve.proxmox.com/pve-docs/chapter-qm.html#_cloud_init_specific_options

I would like a boolean configuration option added to the proxmox_virtual_environment_vm initialization stanza to turn this setting off.

In my specific use case, the default value creates a race condition when using Ansible with Terraform where Ansible playbooks initially fail to update packages because the package manager cannot get a lock (I'm using Debian cloud images so this is the dpkg lock).  If I wait a few minutes and then run Terraform again, the Ansible playbooks will run successfully.

I'm using https://registry.terraform.io/providers/ansible/ansible/latest/docs for the Ansible provider but there may be other use cases where folks would like to change the default behavior.

**Comment by bpg** [comment]
Remove this functionality as per https://github.com/bpg/terraform-provider-proxmox/issues/1291#issuecomment-2111376422

**Comment by CaptaiNiveau** [comment]
Hey! 
I just ran into this. It's not a big issue for us rn, but I'd prefer updating the packages through Ansible, too.
However, reading up on the linked comment, it seems like this won't be implemented for the old vm provider?

Btw, what's the state on the plugin migration, do you need help?

**Comment by dmbrownlee** [comment]
FWIW, the only issue I was running into without this feature is that running Ansible to update the packages too soon after spinning up the VMs would fail because apt could not get a lock if cloud-init was already in the process of updating packages.  I worked around this in Ansible adding `retries` and `until`.

```
- name: Ensure default system packages are up to date
      ansible.builtin.apt:
        upgrade: yes
        autoclean: yes
      register: apt_upgrade
      until: apt_upgrade is success
      retries: 10
      delay: 30
```
