### ISSUE TITLE
Add hostname to scaled VM's 

### ISSUE THREAD

**Issue by breakingflower** [bpg/terraform-provider-proxmox#1094]
I'm new to terraform. Perhaps the solution is simple. 

**Is your feature request related to a problem? Please describe.**
When creating multple VM using the `count` parameter the hostname of the system is always the same. I would like to be able to use a simple hostname parameter to add the hostname programmatically, e.g.

```
resource "proxmox_virtual_environment_vm" "k8s_worker" {
  count     = var.deployment_worker_count
  name      = "${var.deployment_name}-worker-${count.index}"
   ...
  initialization {
    hostname = "${var.deployment_name}-worker-${count.index}" <-- this would be useful
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
    vendor_data_file_id = proxmox_virtual_environment_file.vendor_cloud_config.id
    user_data_file_id = proxmox_virtual_environment_file.k8s_cloud_config.id
  }
```
Similar to the container instantiation [here](https://github.com/bpg/terraform-provider-proxmox/blob/991db34fe2c77a0d4eb3a465f528f6f8119fdc79/docs/resources/virtual_environment_container.md?plain=1#L22) 

This way I can automatically scale the system with non-overlapping hostnames. Especially important in k3s / k8s because they are reliant on hostnames to communicate. 

**Describe the solution you'd like**
Either an option to do this in the highest level of the resource or a way to use the name parameter in cloud-init files. 

**Describe alternatives you've considered**
I tried to use the name variable in cloud init but it is never resolving. I am not sure what I am doing wrong. I've gotten cyclic dependency issues before, e.g. when trying to infer the name from `proxmox_virtual_environment_vm.k8s_worker.name` or something similar. 

**Additional context**
Thanks for the help.

**Comment by maykopetersen** [comment]
Do you use `preserve_hostname: false` in your `cloud.cfg` file?

Read more: https://cloudinit.readthedocs.io/en/latest/reference/modules.html#set-hostname

**Comment by breakingflower** [comment]
That unfortunately did not change anything, the VM boots with default hostname ubuntu. 

I don't use any hostname setting. I'm not sure how I can transfer the value of this name , e.g. `k8s-worker-1`, to the cloud-init yaml files. I'm using the following setup: 
```
resource "proxmox_virtual_environment_vm" "k8s_control" {
  count     = var.deployment_control_count
  name      = "${var.deployment_name}-control-${count.index}"
 ... 

  initialization {
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
    vendor_data_file_id = proxmox_virtual_environment_file.vendor_cloud_config.id
    user_data_file_id = proxmox_virtual_environment_file.k8s_cloud_config.id
  } 
```
i read the yaml files from an proxmox_virtual_environmnet_file 
```

resource "proxmox_virtual_environment_file" "k8s_cloud_config" {
    content_type = "snippets"
    datastore_id = "local"
    node_name    = var.virtual_environment_proxmox_node
    source_file {
        path = "./cloud-init/k8s-node.yaml"
    }
}

resource "proxmox_virtual_environment_file" "vendor_cloud_config" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = var.virtual_environment_proxmox_node
  source_file {
    path = "./cloud-init/vendor.yaml"
  }
}
```
vendor.yaml 
```
#cloud-config
package_update: true
package_upgrade: true
...
runcmd:
    # base settings
    - timedatectl set-timezone Europe/Brussels
    - systemctl enable qemu-guest-agent
    - systemctl start qemu-guest-agent
```
k8s-node.yaml
```
#cloud-config
runcmd:
    # Generate random hostname because hostname is not transferred from terraform
    - hostnamectl set-hostname k8s-$(openssl rand -hex 2) <-- im not sure what else to use here. 
    # It is also recommended that all managed nodes disable firewalls and swap. See K3s Requirements for more information.
    - swapoff -a 
    - ufw disable
    # post install steps
    - reboot 
```
I can't seem to find any variable I can use to substitute the hostname with. Any idea's welcome.

**Comment by maykopetersen** [comment]
The VM's name in Proxmox interface will be the SAME that inside VM, which you see using `hostname` command.
I.e.: if in Proxmox your VM's name is `vm01` and you use Cloud-init, when you access your VM you'll see: `vm01`.
If it doens't happen, the problem is with you cloud-init files.
I'll put an example:
```
manage_etc_hosts: true
users:
   - default
ssh_deletekeys: true 
disable_root: true
preserve_hostname: false
apt:
   preserve_sources_list: true

# The modules that run in the 'init' stage
cloud_init_modules:
 - migrator
 - seed_random
 - bootcmd
 - write-files
 - growpart
 - resizefs
 - disk_setup
 - mounts
 - set_hostname
 - update_hostname
 - update_etc_hosts
 - ca-certs
 - rsyslog
 - users-groups
 - ssh

# The modules that run in the 'config' stage
cloud_config_modules:
 - snap
 - ssh-import-id
 - keyboard
 - locale
 - set-passwords
 - grub-dpkg
 - apt-pipelining
 - apt-configure
 - ntp
 - timezone
 - disable-ec2-metadata
 - runcmd
 - byobu

# The modules that run in the 'final' stage
cloud_final_modules:
 - package-update-upgrade-install
 - fan
 - landscape
 - lxd
 - write-files-deferred
 - puppet
 - chef
 - mcollective
 - salt-minion
 - reset_rmc
 - refresh_rmc_and_interface
 - rightscale_userdata
 - scripts-vendor
 - scripts-per-once
 - scripts-per-boot
 - scripts-per-instance
 - scripts-user
 - ssh-authkey-fingerprints
 - keys-to-console
 - install-hotplug
 - phone-home
 - final-message
 - power-state-change

# System and/or distro specific settings
# (not accessible to handlers/transforms)
system_info:
   # This will affect which distro class gets used
   distro: debian
   Default user name + that default users groups (if added/used)
   default_user:
     name: debian
     lock_passwd: True
     gecos: Debian
     groups: [adm, audio, cdrom, dialout, dip, floppy, netdev, plugdev, sudo, video]
     sudo: ["ALL=(ALL) NOPASSWD:ALL"]
     shell: /bin/bash
    # Don't forget to add your public key here
     ssh_authorized_keys:
       - ssh-rsa xyz
       - ssh-rsa xyz
   # Other config here will be given to the distro class and/or path classes
   paths:
      cloud_dir: /var/lib/cloud/
      templates_dir: /etc/cloud/templates/
   package_mirrors:
     - arches: [default]
       failsafe:
         primary: https://deb.debian.org/debian
         security: https://deb.debian.org/debian-security
   ssh_svcname: ssh
```

If you don't has `preserve_hostname: false` and `set_hostname` configured, it doesn't work.
