### ISSUE TITLE
Cloud-init with hashed passwd not work

### ISSUE THREAD

**Issue by kevin1sMe** [bpg/terraform-provider-proxmox#1117]
**Describe the bug**
When using cloud-init, I encountered an issue where I can log in using the sshkey, but I cannot log in using the specified password. I have tried specifying it as plain_text_passwd, and it works fine, but the passwd method does not work.

**To Reproduce**

Create a resource with the following Terraform configuration:
Define a template_file for user data that sets up the VM's hostname, SSH public key, user, and password.
Use a proxmox_virtual_environment_file resource to create a cloud-init configuration file (user-data.yaml) on a Proxmox node.
Create a virtual machine (proxmox_virtual_environment_vm) on the Proxmox node, specifying the VM name, node name, VM ID, and linking the cloud-init configuration file for user data.
```hcl
data "template_file" "user_data" {
  template = file("${path.module}/cloud-init/user-data.tmpl")
  vars = {
    pubkey   = file(pathexpand("${path.module}/${var.user.sshkeyfile}"))
    hostname = var.vm.vm_name
    user     = var.user.user
    passwd   = var.user.passwd
  }
}

resource "proxmox_virtual_environment_file" "cloud_config" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = "ser5"

  source_raw {
    data      = data.template_file.user_data.rendered
    file_name = "user-data.yaml"
  }
}
resource "proxmox_virtual_environment_vm" "ubuntu_vm" {
  name      = var.vm.vm_name
  node_name = "ser5"
  vm_id     = var.vm.vm_id

  initialization {
    ip_config {
      ipv4 {
   // ...
      }
    }

    user_data_file_id = proxmox_virtual_environment_file.cloud_config.id
  }
```

user-data.tmpl like this:
```hcl
#cloud-config
hostname: ${hostname}
ssh_pwauth: yes
users:
  - default
  - name: ${user}
    passwd: ${passwd}
    lock_passwd: false
    groups:
      - sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${pubkey}
    sudo: ALL=(ALL) NOPASSWD:ALL
```
Run terraform apply to apply the configuration, which creates the VM without errors.
Attempt to log in to the newly created VM using the specified password.
See error: Unable to log in with the specified password, receiving a Login incorrect error message. However, logging in using the SSH key works fine.

The password create by:
```bash
 echo test@123 |  mkpasswd --method=SHA-512 --rounds=4096 --stdin
```

**Expected behavior**
I expected to be able to successfully log into the VM using the specified password. The password was generated using SHA-512 hashing and should have allowed for password-based authentication alongside the option to log in using an SSH key.

**Additional context**

Proxmox configuration: Single node Proxmox.
Provider version: 0.48.1.
Terraform version: v1.7.4.
OS (where you run Terraform from): Ubuntu 22.04 LTS.

**Comment by bpg** [comment]
Hi @kevin1sMe 👋🏼

I'm not certain this issue is related to the provider itself. You've mentioned that SSH login with your configuration works, which indicates the cloud-config file was successfully delivered to the VM. At this point, it's up to the VM to apply the settings defined in that file.

Could it be possible that the template rendering via the `template_file` resource alters the hashed password, especially if it contains special characters? Could you check the file content on the PVE host to verify it rendered as expected? The file should be located in the `/var/lib/vz/snippets/` folder.

**Comment by bpg** [comment]
Reading more on [`template_file`](https://registry.terraform.io/providers/hashicorp/template/latest/docs/data-sources/file), it seems like it may have a special treatment for `$`, which is present in the hashed passwords.

Also, the documentation recommends switching to [`templatefile()` function](https://developer.hashicorp.com/terraform/language/functions/templatefile) for the newer provider versions.

**Comment by kevin1sMe** [comment]
> Hi @kevin1sMe 👋🏼
> 
> I'm not certain this issue is related to the provider itself. You've mentioned that SSH login with your configuration works, which indicates the cloud-config file was successfully delivered to the VM. At this point, it's up to the VM to apply the settings defined in that file.
> 
> Could it be possible that the template rendering via the `template_file` resource alters the hashed password, especially if it contains special characters? Could you check the file content on the PVE host to verify it rendered as expected? The file should be located in the `/var/lib/vz/snippets/` folder.

Thanks for your reply. I had check user-data in VM is correct. like this :
```
ssh_pwauth: yes
users:
  - default
  - name: kevin
    passwd: $6$rounds=4096$t18czZbdAEqLoyEA$9aEWZW62NwruJXyKAOqOASN/1pcjsHUE1ErW5linwXaJ0bFl5ynNIyokq4QE8dxd0JxU0fm2ZIwC.KfXo2GxX1
    lock_passwd: false
    groups:
      - sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3N...
    sudo: ALL=(ALL) NOPASSWD:ALL
  ```
And I check the file `/var/lib/vz/snippets/user-data.yaml`:
```
root@ser5:/var/lib/vz/snippets# cat user-data.yaml


ssh_pwauth: yes
users:
  - default
  - name: kevin
    passwd: $6$rounds=4096$t18czZbdAEqLoyEA$9aEWZW62NwruJXyKAOqOASN/1pcjsHUE1ErW5linwXaJ0bFl5ynNIyokq4QE8dxd0JxU0fm2ZIwC.KfXo2GxX1
    lock_passwd: false
    groups:
      - sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAA...
    sudo: ALL=(ALL) NOPASSWD:ALL
    
```

I've confirmed the `user-data` in the VM appears correct and matches the expected configuration, including the hashed password. I also verified the `/var/lib/vz/snippets/user-data.yaml` file directly on the host, and it aligns with the VM's user-data. This leaves me at an impasse, especially since the password remains unchanged. Any further insights or suggestions would be greatly appreciated.

**Comment by kevin1sMe** [comment]
> Reading more on [`template_file`](https://registry.terraform.io/providers/hashicorp/template/latest/docs/data-sources/file), it seems like it may have a special treatment for `$`, which is present in the hashed passwords.
> 
> Also, the documentation recommends switching to [`templatefile()` function](https://developer.hashicorp.com/terraform/language/functions/templatefile) for the newer provider versions.

I find the user-data in VM is :
```
#cloud-config
hostname: dev
ssh_pwauth: yes
users:
  - default
  - name: kevin
    passwd: $6$rounds=4096$t18czZbdAEqLoyEA$9aEWZW62NwruJXyKAOqOASN/1pcjsHUE1ErW5linwXaJ0bFl5ynNIyokq4QE8dxd0JxU0fm2ZIwC.KfXo2GxX1
    lock_passwd: false
    groups:
      - sudo
    shell: /bin/bash
```

It renders as expected.But the `/etc/shadow` look like this:
```
ubuntu:!$y$j9T$1YbBqG1woUscymccTnvh..$zLf/VK30qwZ2giOgvqqo8S1gzsGIEZqooPUvlHDetNC:19791:0:99999:7:::
lxd:!:19791::::::
kevin:$y$j9T$EXtX/omvU7IUL1VWsKh9Q0$8BabNVmzffKeQFF2eYYDVpLxreT8rCEkNzhDeoLyAZ6:19791:0:99999:7::22889:
```
I don't know why the password is not set. 
Equally strange, why hasn't the default shell been changed to bash and remains as sh?
