### ISSUE TITLE
Not an issue but request for example?

### ISSUE THREAD

**Issue by coltonshipley** [bpg/terraform-provider-proxmox#1174]
I'm using this provider in my homelab. I'm using a centOS9 generic cloud image to provision VM's with. 
However, I'm having issues with ssh access for a provisioner. I'd also like to get away from remote-exec so a cloud-config would be ideal. But I'm not quite sure how to set that up.

I was using this example from Hashicorp - https://github.com/hashicorp/learn-terraform-provisioning/blob/cloudinit/instances/main.tf but it uses the AWS provider and this provider doesn't seem to have a "user_data" stanza in the vm resource.

Any guidance would be awesome. Bonus points if I don't have to upload the file to the proxmox server itself. 

Here is a sample of my main.tf to spin up some nomadagent servers. The idea is to use this as building blocks to make a virtual_machines module after I get this working. Some of the node_logic is due to proxmox not having any sort of DRS features like vmware. 

```hcl
data "proxmox_virtual_environment_nodes" "available_nodes" {}

resource "proxmox_virtual_environment_vm" "virtual_machine" {
  count = 1
  name        = "${format("nomadagent%02d.localdomain", count.index + 4)}"
  node_name   = element(data.proxmox_virtual_environment_nodes.available_nodes.names, count.index)
  tags        = ["terraform"]
  description = "Managed by Terraform."

  agent {
    enabled = true
  }

  initialization {
    datastore_id = "pve-storage-ssd-ceph"

    user_account {
      username = "root"
      password = "securepassword"
    }

    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
  }

  cpu {
    cores = 8
    numa  = true
    type  = "host"    
  }

  memory {
    dedicated = 32768
  }  

  disk {
    datastore_id = "pve-storage-ssd-ceph"
    file_id      = proxmox_virtual_environment_download_file.centos9_cloud_image.id
    interface    = "scsi0"
    iothread     = false
    discard      = "on"
    size         = 80
    ssd          = "true"
  }

  network_device {
    bridge = "vmbr0"
  }  

  provisioner "remote-exec" {
    inline = [
      "sudo rpm --import https://repo.saltproject.io/salt/py3/redhat/9/x86_64/3007/SALTSTACK-GPG-KEY2.pub",
      "curl -fsSL https://repo.saltproject.io/salt/py3/redhat/9/x86_64/3007.repo | sudo tee /etc/yum.repos.d/salt.repo",
      "dnf install -y salt-minion"
    ]

    connection {
      type        = "ssh"
      user        = "root"
      host        = proxmox_virtual_environment_vm.virtual_machine[count.index].ipv4_addresses[1][0]
      password = "securepassword"
      timeout     = "5m"
      agent = false
    }
  }
}

resource "tls_private_key" "root" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "proxmox_virtual_environment_download_file" "centos9_cloud_image" {
  content_type = "iso"
  datastore_id = "unraid"
  node_name    = "pve1"
  url          = "https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2"
  file_name    = "CentOS-Stream-GenericCloud-9-latest.x86_x64.img"
}
```

The remote-exec block is what I would be looking to maybe replace with something like this:

```yaml
#cloud-config

password: securepassword
chpasswd: {expire: False}
ssh_pwauth: True

# Add the SaltStack repository
repo_update: true
repo_upgrade: all
repos:
  saltstack:
    baseurl: https://repo.saltproject.io/py3/redhat/9/x86_64/latest/
    gpgcheck: true
    gpgkey: https://repo.saltproject.io/py3/redhat/9/x86_64/latest/SALTSTACK-GPG-KEY.pub
    enabled: true

# Install Salt Minion
packages:
  - salt-minion
```

I have intentions to explore SSH keys more, but for now pwauth is the 'easier' approach internally.
