### ISSUE TITLE
Disk bandwidth in VM resource

### ISSUE THREAD

**Issue by zaval1976** [bpg/terraform-provider-proxmox#1771]
**Describe the bug**
After first applied some variables in block speed in block disk, not possible add or change other/added variables. 

**To Reproduce**

1. Add in exist VM the speed variable - iops_read for example:
```
   ---
vm-test-vzaval-2222:
- hostname: "vm-test-vzaval-2222"
  node_name: "pmx-test2"
  cpu_cores: "2"
  memory_dedicated: "2"

  initialization:
  - ip_config:
    - ipv4:
      - address: "10.60.50.31/22"
        gateway: "10.60.50.1"

  network_device:
  - bridge: vmbr0

  disk:
  - interface: "virtio0"
    size: "3"
    speed:
    - iops_read: 10

  serial_device:
  - device: socket
```

2. terragrunt run-all plan - is good
```
   09:08:32.682 STDOUT terraform:       ~ disk {
   09:08:32.682 STDOUT terraform:             # (14 unchanged attributes hidden)
   09:08:32.682 STDOUT terraform:           + speed {
   09:08:32.682 STDOUT terraform:               + iops_read            = 10
```

3. After apply 
  
<img width="595" alt="Image" src="https://github.com/user-attachments/assets/807a2749-b5d2-43a6-b907-619bcc5a89b6" />

4. Change iops_read:
```
     speed:
     - iops_read: 100
```

5. terragrunt run-all plan
   
<img width="877" alt="Image" src="https://github.com/user-attachments/assets/5106c12d-dcbc-4d54-a06e-146c7469a734" />

Please also provide a minimal Terraform configuration that reproduces the issue.

```
resource "proxmox_virtual_environment_vm" "this" {
  for_each = merge([
    for vms in local.data: {
      for vm in vms: vm.hostname => vm
    }
  ]...)

----------------

  dynamic "disk" {
    for_each = each.value.disk

    dynamic "speed" {
        for_each = try({
          for speed_key, speed_value in disk.value.speed : speed_key => speed_value
          if speed_value != []
          }, []
        )

        content {
          iops_read            = lookup(speed.value, "iops_read", null)
          iops_read_burstable  = lookup(speed.value, "iops_read_burstable", null)
          iops_write           = lookup(speed.value, "iops_write", null)
          iops_write_burstable = lookup(speed.value, "iops_write_burstable", null)
          read                 = lookup(speed.value, "read", null)
          read_burstable       = lookup(speed.value, "read_burstable", null)
          write                = lookup(speed.value, "write", null)
          write_burstable      = lookup(speed.value, "write_burstable", null)
        }
      }
```

**Expected behavior**
I'm expect changing the iops_read variable

- Single or clustered Proxmox: clustered
- Proxmox version: 8.3.3
- Provider version (ideally it should be the latest version): 0.70.0
- Terraform/OpenTofu version: TF - 1.9.8  Terragrunt - 0.69.1
- OS (where you run Terraform/OpenTofu from): Alpine 3.20.3
- Debug logs (`TF_LOG=DEBUG terraform apply`):
