### ISSUE TITLE
Configuration for proxies for apt

### ISSUE THREAD

**Issue by bigmikef** [bpg/terraform-provider-proxmox#1877]
**Is your feature request related to a problem? Please describe.**
I'm unable to figure out how to write to `/etc/apt/apt.conf` for some proxy config.

**Describe the solution you'd like**
it'd be nice if there was an `proxmox_virtual_environment_apt_proxy` datasource I think?

**Describe alternatives you've considered**
Tried writing the file in cloud-config, but to no success

**Additional context**
I'm new to terraform and this proxmox provider

**Comment by bigmikef** [comment]
I was stumped by two aspects...   First my cloud-config was not allowing logging in from the console because of the default value of `lock_passwd` which need to be `false` to allow logins.

Secondly the following worked for me:
```
#cloud-config
hostname: control-plane
users:
  - name: ubuntu
    groups:
      - sudo
    shell: /bin/bash
    plain_text_passwd: XXXXXXXX
    lock_passwd: false
runcmd:
  - echo 'Acquire::http::Proxy "http://myproxy:port";\nAcquire::https::Proxy "https://myproxy:port";' > /etc/apt/apt.conf
  - apt update
  - apt install -y qemu-guest-agent net-tools
  - timedatectl set-timezone America/Chicago
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - echo "done" > /tmp/cloud-init-done
```
