### ISSUE TITLE
CloudInit configuration is not getting applied in a clone

### ISSUE THREAD

**Issue by some-random-username-123** [bpg/terraform-provider-proxmox#586]
**Describe the bug**
My issue is: When applying a terraform manifest that clones a vm and adds cloud init configuration, the cloudinit image doesnt get regenerated.
I the UI this is done via the Button Regererate image:
![Screenshot_20230922_165942](https://github.com/bpg/terraform-provider-proxmox/assets/145786212/e32d623c-0382-4ec0-a161-733550a34540)
There is also a API call that can do this: [API Refference](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/cloudinit)

![Screenshot_20230922_170233](https://github.com/bpg/terraform-provider-proxmox/assets/145786212/dca9963a-f005-44b6-a044-d639fdbb9d5c)

**To Reproduce**
1. Create a resource with a initialization field
2. Run `terraform apply`
3. Wait until VM runs

My TF Module:
```terraform
...
variable "vm_ci_interface" {
    description = "The Interface for the Cloudinit drive on the VM."
    type = string
    default = "ide0"
}

variable "vm_template_id" {
    description = "The VM ID of the Template that will be cloned."
    type = number
    default = 9000
}

variable "vm_ip_address" {
    description = "The IP adress that the VM has. (use 'dhcp' for automatic IP)"
    type = string
    default = "dhcp"
}

variable "vm_ip_gateway" {
    description = "The IP of the gateway that the VM uses. (when vm_ip_address = 'dhcp' no gateway is used)"
    type = string
    default = ""
}

variable "vm_sa_user_name" {
    description = "The username of the service account that is used on this VM."
    type = string
    default = "sa_ansible"
}

variable "vm_sa_user_password" {
    description = "The password of the service account that is used on this VM."
    type = string
    sensitive = true
}

...
# --------
resource "proxmox_virtual_environment_vm" "almalinux9-basic" {
...
  initialization {
    interface       = var.vm_ci_interface

    ip_config {
      ipv4 {
        address     = var.vm_ip_address
        gateway     = var.vm_ip_address == "dhcp" ? null : var.vm_ip_gateway
      }
    }

    user_account {
      username      = var.vm_sa_user_name
      password      = var.vm_sa_user_password
      keys          = var.vm_sa_user_ssh_keys
    }
  }
......
```

**Screenshots**

**Additional context**
- Single or clustered Proxmox: Single
- Provider version (ideally it should be the latest version): latest
- Terraform version: latest
- OS (where you run Terraform from): Almalinux9 KDE

**Comment by bpg** [comment]
Hi @some-random-username-123! 👋🏼 (nice GH username btw :)

> 4. See error

Could you pls. post here the error that that you saw? 

Also I'd like to clarify whther the original VM that you're cloning has a cloudinit config?

**Comment by some-random-username-123** [comment]
Hi @bpg,
Sure I can give you more insights:

`Also I'd like to clarify whther the original VM that you're cloning has a cloudinit config?`
I Tried both, so i have a emplate with a Cloudinit drive, and i also have a template with no cloudinit drive.
I have the issue with both tamplates.

The exact issue is, that when I clone my vm with the TF provider, after the vm starts the cloudinit config (user and hostname, etc) is not applied in the template.

But when I clone it manually and press the button, all the cloudinit configuration is applied.


I hope this gives you some more insight.

Regards

**Comment by 0xinterface** [comment]
@bpg I took a brief look at the example @some-random-username-123 and apparently the packer template is built by specifying bios to ovmf therefore I think this is related to #575

**Comment by webtroter** [comment]
Hello,

I'm also having this problem

I found this small thread in the Proxmox forums about the Regeneration process. -> https://forum.proxmox.com/threads/regenerate-cloud-init-image-using-ansible.89964/

It is basically a remove/re-add the cloudinit drive.

I hope it could help solve this problem.

Thank you

**Comment by bpg** [comment]
Hey @some-random-username-123 👋🏼 

I'm trying to reproduce this issue with a minimal TF configuration, but everything seems to be working for me (tm)

Here is my template:
```hcl
 resource "proxmox_virtual_environment_vm" "ubuntu_vm" {
  name = "586-template"

  node_name = var.virtual_environment_node_name
  vm_id     = 586
  machine   = "q35"
  bios      = "ovmf"

  agent {
    enabled = true
  }

  efi_disk {
    datastore_id = "local-lvm"
    file_format  = "raw"
    type         = "4m"
  }

  disk {
    datastore_id = "local-lvm"
    file_id      = proxmox_virtual_environment_file.ubuntu_cloud_image.id
    interface    = "virtio0"
    iothread     = true
    discard      = "on"
    size         = 20
  }

  network_device {
    bridge = "vmbr0"
  }

  operating_system {
    type = "l26"
  }

  started = false
}

resource "proxmox_virtual_environment_file" "ubuntu_cloud_image" {
  content_type = "iso"
  datastore_id = "local"
  node_name    = var.virtual_environment_node_name

  source_file {
    path = "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
  }
}

data "local_file" "ssh_public_key" {
  filename = "./id_rsa.pub"
}

resource "proxmox_virtual_environment_file" "cloud_config" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = var.virtual_environment_node_name

  source_raw {
    data = <<EOF
#cloud-config
runcmd:
    - apt update
    - apt install -y qemu-guest-agent net-tools
    - timedatectl set-timezone America/Toronto
    - systemctl enable qemu-guest-agent
    - systemctl start qemu-guest-agent
    - echo "done" > /tmp/vendor-cloud-init-done
    EOF

    file_name = "cloud-config.yaml"
  }
}

resource "proxmox_virtual_environment_vm" "ubuntu_vm_cloned" {
  depends_on = [proxmox_virtual_environment_vm.ubuntu_vm]
  name = "587-cloned"
  node_name = var.virtual_environment_node_name
  vm_id     = 587

  clone {
    vm_id = 586
  }

  initialization {
    #    interface = "scsi0"
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }

    user_account {
      username = "ubuntu"
      keys     = [trimspace(data.local_file.ssh_public_key.content)]
    }

    vendor_data_file_id = proxmox_virtual_environment_file.cloud_config.id
  }

  started = true
}
```

Both VMs got deployed, the "cloned" one has cloudinit:
<img width="813" alt="Screenshot 2023-10-02 at 9 22 01 PM" src="https://github.com/bpg/terraform-provider-proxmox/assets/627562/5c3b9a41-a88d-427e-8b86-c98cd909adf6">

Without pressing "regenerate" there, I was able to login into the VM using configured public key:
<img width="847" alt="Screenshot 2023-10-02 at 9 29 32 PM" src="https://github.com/bpg/terraform-provider-proxmox/assets/627562/d2e5893f-fa81-4a1d-8aa9-726136a76043">

So far, no ideas what could be wrong 🤔

**Comment by bpg** [comment]
@some-random-username-123 [this](https://github.com/some-random-username-123/Proxmox-setup/blob/2eacc4eb816018997f21833596c6867548dc0310/terraform/modules/proxmox/almalinux9-basic/vars.tf#L108) could be the reason. If you're not overriding `vm_ci_interface` variable at apply, the default `ide0` may not work in all configurations. I would recommend switching to `ide2` as per [documentation](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#initialization).

**Comment by some-random-username-123** [comment]
@bpg  Thanks for the response.
I tried it with the other interface and all, but it still wont work. This might be a issue with the distribution, as you areusing ubuntu and it works for you, idk. I will try your ubuntu template and clone next and see it has something to do with the linux distribution, alternatively I will also try and reinstall proxmox and see if this might fixes the issue.

**Comment by bpg** [comment]
Hi @webtroter, @tobiasehlert! 👋🏼

I see you upvoted this issue, do you have a similar problem in your deployments? If yes, would you mind sharing your configuration?

Thanks!

**Comment by webtroter** [comment]
On my part, after your other reply I seemed to made it work (see my
librenms IAC repo)

But I need to retry the provider to be certain or at least report what I
did wrong.

**Comment by tobiasehlert** [comment]
@bpg, well slightly the same.

Example terraform file:
```terraform
resource "proxmox_virtual_environment_file" "vm_cloud_init" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = var.proxmox_settings.node

  source_raw {
    file_name = "cloud-init.user-data.yml"
    data      = file("cloud-init/user-data.yml")
  }
}
```

Example cloud-init/user-data.yml file:
```yaml
#cloud-config
package_upgrade: true
packages:
  - qemu-guest-agent

timezone: Europe/Stockholm
users:
  - name: myusername
    groups: [adm, cdrom, dip, plugdev, lxd, sudo]
    lock-passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINyDI3c8l5Se4w0B2ejL36WJh/PdD5MKKsL9zX0a9sT

power_state:
  delay: now
  mode: reboot
  message: Rebooting after cloud-init completion
  condition: true
```

Proxmox GUI:
![image](https://github.com/bpg/terraform-provider-proxmox/assets/4417850/1b6f0f98-339b-46f7-ab1d-78f15df8cfff)

My expectation was to see my user that was provisioned and the ssh-key, but that's not shown.

I run version Proxmox version 8.0.3 and Terraform provider bpg/proxmox version 0.33.0.

**Comment by tobiasehlert** [comment]
Also (maybe related to cloud-init issue), the _proxmox_virtual_environment_file_ resource for the cloud-init file shown in [comment](https://github.com/bpg/terraform-provider-proxmox/issues/586#issuecomment-1759733335) returns following error to me when applying:
```plain
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: no such file: "local:snippets/cloud-init.user-data.yml"
│ 
│   with proxmox_virtual_environment_file.vm_cloud_init,
│   on cloud_init.tf line 1, in resource "proxmox_virtual_environment_file" "vm_cloud_init":
│    1: resource "proxmox_virtual_environment_file" "vm_cloud_init" {
│ 
╵
```

**Comment by bpg** [comment]
@tobiasehlert could you pls check if `snippets` content type is enabled on the `local` storage? Could be another case of https://github.com/bpg/terraform-provider-proxmox/issues/370#issuecomment-1605266793

**Comment by ratiborusx** [comment]
I've spent a whole day yesterday and quite a bit of overtime experimenting with provider and testing cloud-init functionality specifically and here's my observations.

PART I
In short, CI (cloud-init) cloud-config works as expected at least in userdata part. I didn't test vendor/network/meta because i've got no use for it but i have no reason to believe it won't work.
As i already mentioned somewhere in other issues Proxmox executes cloud-init in somewhat "unconventional" way (at least i'm not used to it compared to how cloud providers deal with it) generating an ISO image for it with the data and mounting it in CD-ROM drive. It also allows to regenerate said image and reapply configuration it contains (for example add a new ssh-key for a user), which is not usually the case with the cloud stuff where cloud-config applied only once at the first boot (or more precisely some modules of CI).

I'm not sure if people are aware but things that Proxmox exposes in it's GUI for Cloud-Init is just a small subset of what cloud-config is capable of. These things are what provider can control via "initialization.dns", "initialization.ip_config" and "initialization.user_account" (btw @bpg there seem to be no way for provider to change "Upgrade packages" option as in GUI?):
![image](https://github.com/bpg/terraform-provider-proxmox/assets/123507924/f8b7ce9f-51d1-4180-8e89-ccc681bd58b1)

But that is in no way a full extent of what could be done via cloud-config and by using provider's arguments like "user_data_file_id" (or network/vendor/meta ones) we could inject our own custom cloud-init cloud-config.
My own mistake (and probably most people with this issue are doing the same) was that i expected to see changes in exposed parameters of cloud-init in Proxmox's GUI - it won't happen although after booting up all the config's parameters would be applied. 
I also do not fully understand that weird magic Proxmox does with cloud-init so it confuses me alot.
For example (and i think THIS is what provider does or emulates when we inject custom cloud-config via "proxmox_virtual_environment_file") i used a console utility "qm" to inject my custom cloud-config into an image and bake it in template afterwards. Documentation also mentions that you could dump cloud-init info contained inside an image but this somehow never worked for me (for CUSTOM cloud-config anyway, but it shows info you put in the GUI fields of cloud-init).
An example:

```
qm set
...
--cicustom [meta=<volume>] [,network=<volume>] [,user=<volume>] [,vendor=<volume>]
           cloud-init: Specify custom files to replace the automatically generated ones at start.
           

# freshly baked template with an injected cloud-config shows nothing for it
root@prox-srv1:~# qm cloudinit dump 1011 user
#cloud-config
hostname: template-ubuntu-22
manage_etc_hosts: true
fqdn: template-ubuntu-22.04
chpasswd:
  expire: False
users:
  - default
package_upgrade: true

# i try to inject cloud-config via console tool but it still shows nothing afterwads
root@prox-srv1:~# qm set 1011 --cicustom "user=local:snippets/userdata-proxmox.yml"
update VM 1011: -cicustom user=local:snippets/userdata-proxmox.yml

root@prox-srv1:~# qm cloudinit dump 1011 user
#cloud-config
hostname: template-ubuntu-22
manage_etc_hosts: true
fqdn: template-ubuntu-22.04
chpasswd:
  expire: False
users:
  - default
package_upgrade: true

# but if i change "User" field of Cloud-Init in Proxmox's GUI it detects changes
root@prox-srv1:~# qm cloudinit dump 1011 user
#cloud-config
hostname: template-ubuntu-22
manage_etc_hosts: true
fqdn: template-ubuntu-22.04
user: WOLOLO <<<< CHANGED!
chpasswd:
  expire: False
users:
  - default
package_upgrade: true
```
In the end it's very weird for me how Proxmox handles cloud-init and i'm not sure what exactly it shows via "qm cloudinit dump". Why it's only reflection of GUI's changes i've no clue...
Maybe some Proxmox guru could explain it or @bpg himself (at least on provider's part, how it handles all that stuff).
The only thing i want to reiterate again - if you inject custom cloud-config into your vm/template do not expect to see any changes in the Proxmox's GUI in Cloud-Init. It won't be show in "qm cloudinit dump" either.

PART II
That's content of my custom cloud-config:
```
ratiborus@HOMEWORLD:~/WORKSPACE/terraform_yandex/proxmox$ cat ../keys/userdata-proxmox.yml
#cloud-config
hostname: px-cloud-config-applied
users:
  - name: tf
    groups: adm,sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAABsomelongstring== tf

packages:
- qemu-guest-agent
package_upgrade: true

runcmd:
  - systemctl enable --now qemu-guest-agent
  - echo "done" > /tmp/user-cloud-init-done

final_message: |
  cloud-init has finished
  version: $version
  timestamp: $timestamp
  datasource: $datasource
  uptime: $uptime
  Ratiborus was here... 
```

And here's 3 different implementations for injecting custom cloud-init cloud-config for userdata, and all of them work:
- cloud-config is kept in a dedicated yaml file and "imported" inside resource directly as external file; probably they way i'd use it if not one small issue i'll mention a bit later...
- cloud-config is kept in a dedicated yaml file and "imported" inside resource as raw data via "file" function of terraform that renders content of an external file; my favourite way of all so far but there may be unintended consequences, i didn't test it much
- cloud-config is kept inline inside terraform manifest and "imported" inside resource as raw data; probably the worst implementation because you keep potentially changeable data inside infrastructure manifest, but may work in some cases where you don't use modules or need a fast way to test something
```
#==================#
#   CLOUD-CONFIG   #
#==================#

resource "proxmox_virtual_environment_file" "cloud_config_userdata" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = "prox-srv1"
  source_file {
    path = "../keys/userdata-proxmox.yml"
  }
}

resource "proxmox_virtual_environment_file" "cloud_config_userdata_raw_file" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = "prox-srv1"
  source_raw {
    data = file("../keys/userdata-proxmox.yml")
    file_name = "userdata-proxmox-raw-file.yml"
  }
}

resource "proxmox_virtual_environment_file" "cloud_config_userdata_raw" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = "prox-srv1"
  source_raw {
    data = <<EOF
#cloud-config
hostname: px-cloud-config-applied
packages:
  - qemu-guest-agent
users:
  - name: tf
    groups: sudo
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-rsa some_long_key
    sudo: ALL=(ALL) NOPASSWD:ALL
runcmd:
    - systemctl enable --now qemu-guest-agent
    - echo "done" > /tmp/user-cloud-init-done
EOF

    file_name = "userdata-proxmox-raw.yml"
  }
}
```

And now about the issue with the first implementation i mentioned earlier.
If you change your external file that is getting imported into Proxmox's snippets datastore these changes are not visible for provider and resource will stay the same. Most likely because provider checks only existence of a file by its name. But if we "import" raw source even as rendered external file then provider sees changes and acts accordingly. The same thing probably happens with cloud images being imported into ISO datastore.
Maybe if provider checked and compared checksum of source and target files every plan and tried to recreate resource (re-download file) if changes are detected it would work better. We could also re-download any distribution's cloud images when they get updated. But i'm not sure if it's something feasible or easily implemented or even wanted by most people.
What do you think, @bpg?

Here's an example:
```
module.proxmox.proxmox_virtual_environment_file.cloud_config_userdata_raw_file: Creating...
module.proxmox.proxmox_virtual_environment_file.cloud_config_userdata: Creating...
module.proxmox.proxmox_virtual_environment_file.cloud_config_userdata: Creation complete after 1s [id=local:snippets/userdata-proxmox.yml]
module.proxmox.proxmox_virtual_environment_file.cloud_config_userdata_raw_file: Creation complete after 1s [id=local:snippets/userdata-proxmox-raw-file.yml]

###
do some changes to source file "../keys/userdata-proxmox.yml", i added installation of vim and htop packages
###

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.proxmox.proxmox_virtual_environment_file.cloud_config_userdata_raw_file must be replaced
-/+ resource "proxmox_virtual_environment_file" "cloud_config_userdata_raw_file" {
      + file_modification_date = (known after apply)
      ~ file_name              = "userdata-proxmox-raw-file.yml" -> (known after apply)
      + file_size              = (known after apply)
      + file_tag               = (known after apply)
      ~ id                     = "local:snippets/userdata-proxmox-raw-file.yml" -> (known after apply)
        # (5 unchanged attributes hidden)

      ~ source_raw {
          ~ data      = <<-EOT # forces replacement
                #cloud-config
                hostname: px-cloud-config-applied
                users:
                  - name: tf
                    groups: adm,sudo
                    shell: /bin/bash
                    sudo: ['ALL=(ALL) NOPASSWD:ALL']
                    ssh-authorized-keys:
                      - ssh-rsa AAAABsomelongstring== tf

                packages:
                - qemu-guest-agent
              + - vim
              + - htop
                package_upgrade: true

                runcmd:
                  - systemctl enable --now qemu-guest-agent
                  - echo "done" > /tmp/user-cloud-init-done

                final_message: |
                  cloud-init has finished
                  version: $version
                  timestamp: $timestamp
                  datasource: $datasource
                  uptime: $uptime
                  Ratiborus was here...
            EOT
            # (2 unchanged attributes hidden)
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```
